name: Build

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: lukka/get-cmake@latest

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10
      with:
        configurePreset: cfg
        buildPreset: bld
        buildPresetAdditionalArgs: "['--config Release']"

    - name: Build AppImage
      run: |
        sudo apt install libfuse2
        cd "${{github.workspace}}/deploy"
        chmod +x linux-appimage.sh
        ./linux-appimage.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "guu-linux"
        path: "${{github.workspace}}/deploy/out"

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: lukka/get-cmake@latest

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{github.workspace}}\qt\'

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10
      with:
        configurePreset: cfg
        buildPreset: bld
        buildPresetAdditionalArgs: "['--config Release']"

    - name: Run windeployqt
      run: ${{env.QT_ROOT_DIR}}\bin\windeployqt.exe "${{github.workspace}}\build\src\Release\guu-cpp.exe" --release

    - name: Compile Inno Installer
      run: |
        choco install InnoSetup -y --no-progress --allow-unofficial
        cd ${{github.workspace}}\deploy
        iscc '${{github.workspace}}\deploy\windows-inst.iss' /O${{github.workspace}}\out

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "guu-windows"
        path: '${{github.workspace}}\out'

  build-mac:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: lukka/get-cmake@latest

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        dir: '${{github.workspace}}/qt/'
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10
      with:
        configurePreset: cfg
        buildPreset: bld
        buildPresetAdditionalArgs: "['--config Release']"

    - name: Build DMG
      run: |
        mv ${{github.workspace}}/build/src/Release/guu-cpp.app "${{github.workspace}}/build/src/Release/GayTor.rent Upload Utility.app"
        ${{env.QT_ROOT_DIR}}/bin/macdeployqt "${{github.workspace}}/build/src/Release/GayTor.rent Upload Utility.app" -dmg
        rm -r ${{github.workspace}}/build/src/Release/*.app

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "guu-mac"
        path: "${{github.workspace}}/build/src/Release"